[env]
SURREAL_DB_URL = "surrealkv://{{config_root}}/root-solar"
SURREAL_NAMESPACE = "root-solar"
SURREAL_DATABASE = "root-solar"

[tools]
pnpm = "latest"

[tasks.dev]
run = "pnpm rsbuild dev"

[tasks.start]
run = "pnpm start"
