apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-solar
  namespace: root-solar
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: root-solar
  template:
    metadata:
      labels:
        app: root-solar
        app.kubernetes.io/name: root-solar
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: initPermissions
          image: alpine:3.20
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              mkdir -p /data && chown -R 1000:1000 /data
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: app
          image: root-solar:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: root-solar-config
                  key: PORT
            - name: DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: root-solar-config
                  key: DB_PATH
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: "0.5"
              memory: 256Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: data
          persistenVolumeClaim:
            claimName: root-solar-pvc
