apiVersion: v1
kind: PersistentVolume
metadata:
  name: root-solar-pv
  labels:
    app: root-solar
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
  hostPath:
    path: /var/lib/root-solar/data
    type: DirectoryOrCreate
