apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-solar-pvc
  namespace: root-solar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-hostpath
  volumeName: root-solar-pv
